version: 2
jobs:
  build:
    working_directory: ~/circleci-koa-demo
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm i
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Say my name
          command: |
            echo "Hello, Heisenberg!"
